### ISSUE TITLE
The Glossary section is empty

### ISSUE THREAD

**Issue by Ferenc-** [SovereignCloudStack/contributor-guide#33]
The Glossary section is empty, I guess we should complete it or remove it:
https://github.com/SovereignCloudStack/contributor-guide/blob/master/source/glossary.rst
http://scs.community/docs/contributor/glossary.html

**Comment by berendt** [comment]
This was done on purpose so that the chapter is already there when a glossary is needed in the future. It may not make as much sense in the Contributor Guide. I have no objection to removing it.

**Comment by garloff** [comment]
Let's keep it for now.
