### ISSUE TITLE
Abandon this repository

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/contributor-guide#34]
We should try to reduce the number of repositories and different static site generators. My proposal is to:

- merge the markup documents of this repository to `SovereignCloudStack/Docs`
- archive this repository
- add `SovereignCloudStack/Docs` as submodule of `SovereignCloudStack/website` and let Jekyll build the docs as beautiful html pages (needs some minor work which I would tackle!)

Would you agree with this proposal?

**Comment by berendt** [comment]
Good idea to reduce the number of repositories. But I think it would be good if we create a blueprint before the reduction and talk about it briefly in one of the meetings.

**Comment by itrich** [comment]
See PR at Docs repository: https://github.com/SovereignCloudStack/Docs/pull/57

**Comment by itrich** [comment]
Fixed by https://github.com/SovereignCloudStack/Docs/pull/57
